# Compiler
CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -Iinclude

# Target executable
TARGET = simulation

# Source files
SRC = source/main.cpp source/system.cpp source/disk.cpp

# Object files
OBJ = $(SRC:.cpp=.o)

# Default rule
all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJ)

run: $(TARGET)
	mkdir -p confs
	./$(TARGET)

clean:
	rm -f $(OBJ) $(TARGET)
